### ISSUE TITLE
Interested in a data update to 2017?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [mine-cetinkaya-rundel/ukbabynames#1]
I have a PR ready to go if you would be interested in updating the package to include data up to 2017 (most recent data available as of today).

If so, what version number should I use?

**Comment by leeper** [comment]
@mine-cetinkaya-rundel Do you want to just take over this package?

**Comment by mine-cetinkaya-rundel** [comment]
Sure, if you're no longer interested in maintaining it, I'd be happy to. I have a vested interest in keeping it updated.

**Comment by leeper** [comment]
I'll give you edit rights - I would be thrilled if you'd like to take over maintaining it!

**Comment by mine-cetinkaya-rundel** [comment]
Sounds good, happy to take over. Thank you!

**Comment by leeper** [comment]
Yay! Happy to move this over to your account - just let me know.

**Comment by mine-cetinkaya-rundel** [comment]
Sounds good, you can transfer and I'll accept on my end.

**Comment by leeper** [comment]
I think you need to delete your fork before I can transfer, so you may want to send and merge your PR first.

**Comment by mine-cetinkaya-rundel** [comment]
Done!

**Comment by leeper** [comment]
Done

**Comment by mine-cetinkaya-rundel** [comment]
Merci!
