### ISSUE TITLE
Scottish baby names

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [mine-cetinkaya-rundel/ukbabynames#2]
I was able to locate a similar data source to the one you used for Scottish baby names. I was wondering if it might make sense to include those in the counts here as well since the package is called UK baby names.

Pro: Package is called ukbabynames so it makes sense to include Scottish names here as opposed to in a separate package.

Con: This will change past counts, hence making the package not backwards compatible. One approach is to include Scottish baby names as a separate data frame in the package, but then I'm worried the ukbabynames name will be misleading for the existing data frame.

If there is no desire to include those here, I'm happy to collect them in a separate package.

**Comment by dragosmg** [comment]
Northern Ireland has a separate statistics authority that publishes similar data. The latest release can be found [here](https://www.nisra.gov.uk/publications/baby-names-2017). 

I totally agree with your Pro. It makes sense to include Scotland and Northern Ireland.

The only downside I can think of: population of England is much bigger than that of Scotland or Northern Ireland, thus the counts for top Scottish or Northern Irish names will be comparatively smaller. 

Including them as separate data frames might make more sense.

Maybe include 4 data frames:
1. new UK = England & Wales + Northern Ireland + Scotland (bind rows and add an extra Country variable)
2. England & Wales - as published by the Office for National Statistics (ONS). This will be similar to the old version of the package
3. Scotland - as published by the National Records of Scotland
4. Northern Ireland

Or include just number 1 which people can split by country if they wish, aggregate up to get the UK figures or compare across countries.  

What do you think?

With regards to the date of publication, I think the Scottish one is published in March (for the previous year), the Northern Irish one in August and the ONS one is published in late September. It might make sense to schedule a minor release for October to update all that need updating.

**Comment by mine-cetinkaya-rundel** [comment]
@dragosmg This is along the lines of what I was thinking as well -- making separate data frames for each source and then adding combining them with a new column in the `ukbabynames` data frame. I'll work on getting these together. The timeline makes sense as well, though I might make a release soon with what's there and then a re-release in regular intervals for future.

Thanks for the NI link!

**Comment by dragosmg** [comment]
@mine-cetinkaya-rundel Happy to contribute if need be.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the pointers @dragosmg, we got these in and the new version is now on CRAN!
